[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
  "solmate/=lib/solmate/src/"
]

[profile.ci]
optimizer = false
fuzz_runs = 256
gas_reports = []

[profile.ci.rpc_storage_caching]
chains = ["mainnet"]
endpoints = "remote"
